# Site settings
title: Turtle Express
email: texbluesinfo@gmail.com
description: >
  Turtle Express ist eine Akustik-Blues/Rock Band aus Koblenz.
  Wir covern alles von Motörhead über Jimmy Hendrix bis Johnny Cash.
baseurl: ""
url: "http://localhost:4000" # the base hostname & protocol for your site
github: turbopope/tex
gems:
  - jekyll-last-modified-at
  - jekyll-assets
assets:
  sources:
    - _assets
    - _assets/scss

# Build settings
markdown: kramdown
