# Site settings
title: Turtle Express
email: texbluesinfo@gmail.com
description: >
  Turtle Express ist eine Akustik-Blues/Rock Cover-Band aus dem Raum Koblenz.
baseurl: ""
url: "http://localhost:4000" # the base hostname & protocol for your site
github: turbopope/tex
gems:
  - jekyll-last-modified-at

# Build settings
markdown: kramdown
