# Site settings
title: Turtle Express
email: texbluesinfo@gmail.com
description: >
  Turtle Express ist eine Akustik-Blues/Rock Band aus Koblenz.
  Wir covern alles von Motörhead über Jimmy Hendrix bis Johnny Cash.
baseurl: ""
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username:  turbopope
gems:
  - jekyll-last-modified-at

# Build settings
markdown: kramdown
